CREATE TABLE IF NOT EXISTS scheduler_leases (
    lease_name VARCHAR(128) PRIMARY KEY,
    owner_id VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
